# Generated by Django 5.1.2 on 2024-10-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_providers'),
    ]

    operations = [
        migrations.AddField(
            model_name='providers',
            name='credentials',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
