# Generated by Django 5.1.2 on 2024-10-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_providers_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='providers',
            name='priority',
            field=models.IntegerField(default=1),
        ),
    ]
