# Generated by Django 5.1.2 on 2024-10-13 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_providers_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='load_historical_data',
            field=models.BooleanField(default=True),
        ),
    ]
