# Generated by Django 5.1.2 on 2024-10-13 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_currency_load_historical_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='load_historical_data',
            field=models.BooleanField(default=False),
        ),
    ]
